# Generated by Django 6.0 on 2025-12-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_actor_bio_en_actor_bio_ru_actor_full_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_status',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=30),
        ),
    ]
